### ISSUE TITLE
Error when creating/entering a project

### ISSUE THREAD

**Issue by dragonCASTjosh** [JSandusky/UrhoAngelscriptIDE#7] opened 2015-08-09 09:22 UTC
When i open or create a project it will take me to the screen shown bellow, upon going back and repeating the task the project opens as intended. 
![capture](https://cloud.githubusercontent.com/assets/3044415/9154307/76f4b7c8-3e80-11e5-8bc6-5fafa0a0f8bf.PNG)

**Comment by JSandusky** [comment] 2015-08-09 22:47
Thanks, I've reproduced. I'll push a fix shortly.

**Comment by JSandusky** [comment] 2015-08-10 00:13
Fix committed, caused by missing a "bin" folder in the same folder as the program exe.

That portion of "troubleshooting" and other instructions is unclear. Wherever asDevelop,exe is create a folder named "bin" and in that's where you copy the AngelScriptAPI.h and ScriptAPI.dox files from the Docs folder of your Urho3D checkout (compiled script compiler goes there too if you want to compile).

**Closed by JSandusky** 2015-08-10 00:13 UTC
